-- Todas as corridas onde apenas 3 equipes pontuaram
SELECT 
	A.CORRIDA_ID AS 'CORRIDA_ID', 
	C.TEMPORADA_ANO AS 'TEMPORADA_ANO', 
	C.NOME AS 'CIRCUITO',
	C.DATA AS 'DATA'
FROM
	(
	SELECT HE.CORRIDA_ID, COUNT(HE.EQUIPE_ID) AS QTY
	FROM 
		HISTORICO_EQUIPE HE
	WHERE 
		HE.PONTUACAO > 0
	GROUP BY 
		HE.CORRIDA_ID, HE.EQUIPE_ID
	) A
	INNER JOIN CORRIDA C ON C.ID = A.CORRIDA_ID
GROUP BY A.CORRIDA_ID
HAVING SUM(A.QTY) = 3;