-- Pontuação média dos 20 melhores pilotos das últimas 10 temporadas
SELECT MIN(TEMPORADA_ANO) AS 'YEAR_MIN', MAX(TEMPORADA_ANO) AS 'YEAR_MAX' FROM CORRIDA;
SELECT STRFTIME('%Y', 'NOW', '-10 YEARS') AS 'YEAR'; -- 10th YEAR

SELECT 
    P.NOME || ' ' || P.SOBRENOME AS 'PILOTO',
    P.NACIONALIDADE AS 'NACIONALIDADE',
    ROUND(AVG(HP.PONTUACAO),2) AS 'PONTUACAO_MEDIA'
FROM 
    HISTORICO_PILOTO HP 
	INNER JOIN CORRIDA C ON C.ID = HP.CORRIDA_ID
    INNER JOIN PILOTO P ON HP.PILOTO_ID = P.ID
WHERE 
	C.TEMPORADA_ANO >= (SELECT STRFTIME('%Y', 'NOW', '-10 YEARS') AS 'YEAR') 
	AND C.TEMPORADA_ANO <= (SELECT MAX(ANO) FROM TEMPORADA)
GROUP BY P.ID
ORDER BY AVG(HP.PONTUACAO) DESC
LIMIT 20;